const LEVELS = [
  [
    "                            AA",
    "              A    AAAAA    BB",
    "          A   B     BBBB    BB",
    "   A    AAB   B             BB",
    "       ABBB   BA          @ BB",
    "AAAAAAABBBBAAABBAAAAAAAAAAAABB",
    "B.",
    "B.",
    "B.",
    "B.",
  ],
  [ 
    "               1",
    "AA            AAA",
    "BBA          ABBBA         II",
    "BBBA        ABBBBBA        II",
    "BBBB        BBBBBBB        II",
    "BBBBA      ABBBBBBBA       II",
    "BBBBBAAAAAABBBBBBBBBA.",
    "B.",
    "B.",
    "B.",
    "B.",
  ],
  [
    "",
    "                        A.",
    "                             B",
    "                             B",
    "                             B",
    "                             B",
    "                             B",
    "                             B",
    "                             B",
    "                    AAAA     B",
    "                   ABBBB     B",
    "                   BBBBB     B",
    "                  ABBBBB     B",
    "                 ABBBBBB     B",
    "               AABBB BBB  AAAB",
    "             AABBBB  BBB    II",
    "       AAA   BBBB    BBB    II",
    "      ABBBA  BB       BB    II",
    "      BBBBB        @  BB    II",
    "AAAAAABBBBBAAAAAAAAAAABBA.",
    "B.",
    "B.",
    "B.",
    "B.",
  ],
  [
    "A",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B               SS",
    "B               SS    SSS",
    "B                     SSS",
    "B              S",
    "",
    "",
    "             S",
    "AAAAA    SS",
    "BBBBB    SS",
    "SBSBB",
    "SSSSB",
    "SSSSS",
  ],
  [
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                         C   C",
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                       2     C",
    "                      CCC    C",
    "                             C",
    "                             C",
    "                           C C",
    "      C                      C",
    "                             C",
    "                            C",
    "CCCC     CCCC   C   CCC    C  ",
  ],
  [
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C             CC",
    "C             CC",
    "C             CC",
    "C             CC",
    "C             CC",
    "C             CC           C",
    "C             CC           C",
    "C             CC           C",
    "C             II           C",
    "C             II           C",
    "C             II           C",
    "C             II           C",
    "C     C      AAAA    CCCC",
    "",
    "",
    "CCCC",
  ],
  [
    "          @                  A",
    "        AAAAAA               B",
    "        BBII                AB",
    "        BBII                B.",
    "        BBII                B.",
    "        BBII               AB.",
    "        BBB AA             B.",
    "        BB  BB            AB.",
    "        BB  BB          AAB.",
    "         B  BB       AAAB.",
    "            BB    AAAB.",
    "            BB    B.",
    "            BB    B.",
    "            BB    B.",
    "CCCCCCCCCCC BB    B.",
  ],
  [
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "A                            $",
    "BAA                          $",
    "BBBA                         $",
    "BBBB                         $",
    "BBBB                         $",
    "B*BB      A#                 $",
    "BABB     ABB           A     $",
    "BBBB     BBS           B     $",
    "BBB       SS          BB     $",
    "BB        S            BB    $",
    "BS                     BB    $",
    "SS#                    B     $",
    "SSS             C#C          $",
    "SSSS                         $",
    "SSSS     CCC           #S    $",
  ],
  [
    "",
    "",
    "",
    "                         *AA",
    "                       SSABSSS",
    "                      S.",
    "                      S.",
    "                      SSS",
    "                      SSS",
    "                      SSS",
    "                      $$$",
    "                      $$$",
    "                      $$$",
    "          P.",
    "      P.",
    "   P.",
    " P.",
    "P.",
  ]
];

for (let i = 0; i < LEVELS.length; i++){
  LEVELS[i].reverse();
}
