export enum KeyNames {
  CAMPUS_USERNAME = "CAMPUS_USERNAME",
  CAMPUS_PASSWORD = "CAMPUS_PASSWORD",
  TCI_USERNAME = "TCI_USERNAME",
  TCI_PASSWORD = "TCI_PASSWORD",
  TCI_TEACHER = "TCI_TEACHER",
  BIM_USERNAME = "BIM_USERNAME",
  BIM_PASSWORD = "BIM_PASSWORD",
}
