/// <reference path="game.d.ts" />
const LEVELS = [
    // 1, coin
    [
        "                            AA",
        "              A    AAAAA    BB",
        "          A   B     BBBB    BB",
        "        AAB   B             BB",
        "       ABBB   BA          @ BB",
        "AAAAAAABBBBAAABBAAAAAAAAAAAABB",
        "B.",
        "B.",
        "B.",
        "B.",
    ],
    // 2, fire suit
    [
        "               1",
        "AA            AAA",
        "BBA          ABBBA         II",
        "BBBA        ABBBBBA        II",
        "BBBB        BBBBBBB        II",
        "BBBBA      ABBBBBBBA       II",
        "BBBBBAAAAAABBBBBBBBBA.",
        "B.",
        "B.",
        "B.",
        "B.",
    ],
    // 3, coin, ice
    [
        "",
        "                        A.",
        "                             B",
        "                             B",
        "                             B",
        "                             B",
        "                             B",
        "                             B",
        "                             B",
        "                    AAAA     B",
        "                   ABBBB     B",
        "                   BBBBB     B",
        "                  ABBBBB     B",
        "                 ABBBBBB     B",
        "               AABBB BBB  AAAB",
        "             AABBBB  BBB    II",
        "       AAA   BBBB    BBB    II",
        "      ABBBA  BB       BB    II",
        "      BBBBB        @  BB    II",
        "AAAAAABBBBBAAAAAAAAAAABBA.",
        "B.",
        "B.",
        "B.",
        "B.",
    ],
    // 4
    [
        "A",
        "B",
        "B",
        "B",
        "B",
        "B",
        "B",
        "B",
        "B",
        "B",
        "B",
        "B               SS",
        "B               SS    SSS",
        "B                     SSS",
        "B              S",
        "B",
        "",
        "             S",
        "AAAAA    SS",
        "BBBBB    SS",
        "SBSBB",
        "SSSSB",
        "SSSSS",
    ],
    // 5, jump suit
    [
        "                             C",
        "                             C",
        "                             C",
        "                             C",
        "                             C",
        "                             C",
        "                             C",
        "                         C   C",
        "                             C",
        "                             C",
        "                             C",
        "                             C",
        "                       2     C",
        "                      CCC    C",
        "                             C",
        "                             C",
        "                           C C",
        "      C                      C",
        "                             C",
        "                            C",
        "CCCC     CCCC   C   CCC    C  ",
    ],
    // 6, ice
    [
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C             CC",
        "C             CC",
        "C             CC",
        "C             CC",
        "C             CC",
        "C             CC           C",
        "C             CC           C",
        "C             CC           C",
        "C             II           C",
        "C             II           C",
        "C             II           C",
        "C             II           C",
        "C     C      AAAA    CCCC",
        "",
        "",
        "CCCC",
    ],
    // 7, coin
    [
        "          @                  A",
        "        AAAAAA               B",
        "        BBII                AB",
        "        BBII                B.",
        "        BBII                B.",
        "        BBII               AB.",
        "        BBB AA             B.",
        "        BB  BB            AB.",
        "        BB  BB          AAB.",
        "         B  BB       AAAB.",
        "            BB    AAAB.",
        "            BB    B.",
        "            BB    B.",
        "            BB    B.",
        "CCCCCCCCCCC BB    B.",
    ],
    // 8, hammer suit, hammer switch, switches
    [
        "                             $",
        "                             $",
        "                             $",
        "                             $",
        "                             $",
        "                             $",
        "                             $",
        "                             $",
        "A                            $",
        "BAA                          $",
        "BBBA                         $",
        "BBBB                         $",
        "BBBB                         $",
        "B*BB      A#                 $",
        "BABB     ABB           A     $",
        "BBBB     BBS           B     $",
        "BBB       SS          BB     $",
        "BB        S            BB    $",
        "BS                     BB    $",
        "SS#                    B     $",
        "SSS             C#C          $",
        "SSSS                         $",
        "SSSS     CCC           #S    $",
    ],
    // 9, hammer switches
    [
        "",
        "",
        "",
        "                         *AA",
        "                       SSABSSS",
        "                      S.",
        "                      S.",
        "                      SSS",
        "                      SSS",
        "                      SSS",
        "                      $$$",
        "                      $$$",
        "                      $$$",
        "          P.",
        "      P.",
        "   P.",
        " P.",
        "P.",
    ],
    // 10, spikes, new music
    [
        "       SS  SS",
        "       SS  SSS",
        "       SS  SSSSS",
        "       SS  SSSSSSS",
        "       SS  SSSSSSSSS",
        "       SS  SSSSSSSSSSSS",
        "       SS  SSSSSSSSSSSSSSS",
        "       SS  SS   S.",
        "       VV  SS   SSSSS",
        "           SS ^",
        "       SS  SS SSSSSSS S S S S",
        "       SS  SS      SS^S S S S",
        "       SS  SSSSSSS SSSS^S S S",
        "       SS  SSSSSSS SSSSSS^S S",
        "       SS  SSSSSSS SSSSSSSS^S",
        "       SS  SSS   S SSSSSSSSSS^",
        "       SS    V     S.",
        "       SS      ^   S.",
        "PPPPPPPSS^^SSSSSSP.",
        "PPPPPPPSSSSSSSSSPPSP.",
        "PPPPPPPSSSSSSP.",
        "PPPPPPPPPPPPPPSP.",
        "PPPPPPPPPPPPPPPPPSP.",
    ],
    // 11, castle, sliding door, guard
    [
        "        O O O O!         O O O",
        "        OOOOOOOO         O.",
        "        OOOOOOOO O O O O O.",
        "        O.",
        "        O.",
        "        O.",
        "        O.",
        "        O.",
        "        O.",
        "        OOOOOOOOOOO   O.",
        "        OOOOOOOOO       O.",
        "        OOOOOOOO         O.",
        "        OOOOOOO           O.",
        "        OOOOOOO           O.",
        "        OOOOOOO           O.",
        "         OOOOO             O.",
        "           |",
        "PPPPP      |",
        "PPPPPPPPR.",
        "PPPPPPPPG.",
    ],
    // 12, castle, 2 guards, sliding door
    [
        "",
        "",
        "",
        "",
        "O O O O                O O O!O",
        "OOOOOOOO               O.",
        "OOOOOOOO O O O O O O O O.",
        "O.",
        "O.",
        "O.",
        "O.",
        "O.",
        "O.",
        "OOOOOOOOOO          O.",
        "OOOOOOO                O.",
        "OOOOO                    O.",
        "OOOOO                    O.",
        "OOOO                      O.",
        "OOOO                      O.",
        "OOO                        O.",
        "                            |",
        "                   !        |",
        "R.",
        "G.",
    ],
    // 13, castle, flash, ult guard
    [
        "",
        "",
        "",
        "",
        "Z Z Z Z                Z Z Z Z",
        "ZZZZZZZZ               Z.",
        "ZZZZZZZZ Z Z Z Z Z Z Z Z.",
        "Z.",
        "Z.",
        "Z.",
        "Z.",
        "Z.",
        "Z.",
        "ZZZZZZZZZZ          Z.",
        "ZZZZZZZ                Z.",
        "ZZZZZ                    Z.",
        "ZZZZZ                    Z.",
        "ZZZZ                      Z.",
        "ZZZZ                      Z.",
        "ZZZ                        Z.",
        "                            |",
        "               !            |",
        "Y.",
        "Z.",
    ],
    // 14, THE END FINALLY
    [
        "             A.",
        "              B.",
        "                B.",
        "                  B.",
        "O O O O             B.",
        "OOOOOOO              B.",
        "OOOOOOO               B.",
        "OOOOOOO BBB B   B BBB  B.",
        "OOOOOOO B   BB  B B  B  B.",
        "OOOOOOO BBB B B B B  B   B.",
        "OOOOOOO B   B  BB B  B    B.",
        "OOOOOOO BBB B   B BBB      B.",
        "OOOOOOO                     B.",
        "OOOOOOO                     B.",
        "OOOOOOO                     B.",
        "OOOOOOO                      B",
        "OOOOOOO                      B",
        "OOOOOOO                     AB",
        "OOOOOO                      B.",
        "                            B.",
        "              AAA          AB.",
        "RRRRRRAAAAAAAABBBAAAAAAAAAAB.",
        "GGGGGGB.",
    ],
];
for (let level of LEVELS) {
    level.reverse();
}
