/// <reference path="game.d.ts" />

const LEVELS:string[][] = [
  // 1, coin
  [
    "                            AA",
    "              A    AAAAA    BB",
    "          A   B     BBBB    BB",
    "        AAB   B             BB",
    "       ABBB   BA          @ BB",
    "AAAAAAABBBBAAABBAAAAAAAAAAAABB",
    "B.",
    "B.",
    "B.",
    "B.",
  ],
  // 2, fire suit
  [ 
    "               1",
    "AA            AAA",
    "BBA          ABBBA         II",
    "BBBA        ABBBBBA        II",
    "BBBB        BBBBBBB        II",
    "BBBBA      ABBBBBBBA       II",
    "BBBBBAAAAAABBBBBBBBBA.",
    "B.",
    "B.",
    "B.",
    "B.",
  ],
  // 3, coin, ice
  [
    "",
    "                        A.",
    "                             B",
    "                             B",
    "                             B",
    "                             B",
    "                             B",
    "                             B",
    "                             B",
    "                    AAAA     B",
    "                   ABBBB     B",
    "                   BBBBB     B",
    "                  ABBBBB     B",
    "                 ABBBBBB     B",
    "               AABBB BBB  AAAB",
    "             AABBBB  BBB    II",
    "       AAA   BBBB    BBB    II",
    "      ABBBA  BB       BB    II",
    "      BBBBB        @  BB    II",
    "AAAAAABBBBBAAAAAAAAAAABBA.",
    "B.",
    "B.",
    "B.",
    "B.",
  ],
  // 4
  [
    "A",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B",
    "B               SS",
    "B               SS    SSS",
    "B                     SSS",
    "B              S",
    "B",
    "",
    "             S",
    "AAAAA    SS",
    "BBBBB    SS",
    "SBSBB",
    "SSSSB",
    "SSSSS",
  ],
  // 5, jump suit
  [
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                         C   C",
    "                             C",
    "                             C",
    "                             C",
    "                             C",
    "                       2     C",
    "                      CCC    C",
    "                             C",
    "                             C",
    "                           C C",
    "      C                      C",
    "                             C",
    "                            C",
    "CCCC     CCCC   C   CCC    C  ",
  ],
  // 6, ice
  [
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C             CC",
    "C             CC",
    "C             CC",
    "C             CC",
    "C             CC",
    "C             CC           C",
    "C             CC           C",
    "C             CC           C",
    "C             II           C",
    "C             II           C",
    "C             II           C",
    "C             II           C",
    "C     C      AAAA    CCCC",
    "",
    "",
    "CCCC",
  ],
  // 7, coin
  [
    "          @                  A",
    "        AAAAAA               B",
    "        BBII                AB",
    "        BBII                B.",
    "        BBII                B.",
    "        BBII               AB.",
    "        BBB AA             B.",
    "        BB  BB            AB.",
    "        BB  BB          AAB.",
    "         B  BB       AAAB.",
    "            BB    AAAB.",
    "            BB    B.",
    "            BB    B.",
    "            BB    B.",
    "CCCCCCCCCCC BB    B.",
  ],
  // 8, hammer suit, hammer switch, switches
  [
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "                             $",
    "A                            $",
    "BAA                          $",
    "BBBA                         $",
    "BBBB                         $",
    "BBBB                         $",
    "B*BB      A#                 $",
    "BABB     ABB           A     $",
    "BBBB     BBS           B     $",
    "BBB       SS          BB     $",
    "BB        S            BB    $",
    "BS                     BB    $",
    "SS#                    B     $",
    "SSS             C#C          $",
    "SSSS                         $",
    "SSSS     CCC           #S    $",
  ],
  // 9, hammer switches
  [
    "",
    "",
    "",
    "                         *AA",
    "                       SSABSSS",
    "                      S.",
    "                      S.",
    "                      SSS",
    "                      SSS",
    "                      SSS",
    "                      $$$",
    "                      $$$",
    "                      $$$",
    "          P.",
    "      P.",
    "   P.",
    " P.",
    "P.",
  ],
  // 10, spikes, new music
  [
    "       SS  SS",
    "       SS  SSS",
    "       SS  SSSSS",
    "       SS  SSSSSSS",
    "       SS  SSSSSSSSS",
    "       SS  SSSSSSSSSSSS",
    "       SS  SSSSSSSSSSSSSSS",
    "       SS  SS   S.",
    "       VV  SS   SSSSS",
    "           SS ^",
    "       SS  SS SSSSSSS S S S S",
    "       SS  SS      SS^S S S S",
    "       SS  SSSSSSS SSSS^S S S",
    "       SS  SSSSSSS SSSSSS^S S",
    "       SS  SSSSSSS SSSSSSSS^S",
    "       SS  SSS   S SSSSSSSSSS^",
    "       SS    V     S.",
    "       SS      ^   S.",
    "PPPPPPPSS^^SSSSSSP.",
    "PPPPPPPSSSSSSSSSPPSP.",
    "PPPPPPPSSSSSSP.",
    "PPPPPPPPPPPPPPSP.",
    "PPPPPPPPPPPPPPPPPSP.",
  ]
];

for (let level of LEVELS){
  level.reverse();
}
